# Generated by Django 4.2.10 on 2024-03-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('auto_field', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.BinaryField()),
                ('number', models.IntegerField()),
                ('agreed', models.BooleanField()),
                ('name', models.CharField(max_length=50)),
                ('published', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField()),
                ('price', models.PositiveBigIntegerField()),
                ('slug', models.SlugField()),
                ('time_in_day', models.TimeField()),
                ('url', models.URLField()),
            ],
        ),
    ]
