# Generated by Django 4.2.10 on 2024-03-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='agreed',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='file',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='number',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='published',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='time_in_day',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='url',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='big_integer_field',
            field=models.BigIntegerField(default=690),
        ),
    ]
